### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택 할 수 있도록 하는 인덱싱에 대한 알아보자
#### 1.특정한 데이터만 추출
#### 2.슬라이싱(Slicing)
#### 3.팬시 인덱싱(Fancy Indexing)
#### 4.불린 인덱싱(Boolean Indexing)

In [7]:
pip install numpy

     --------------------------------------- 14.8/14.8 MB 65.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [16]:
# 1~9까지 1차원 ndarray 생성 -  np.arange
array1 = np.arange(1,10)
array1
value = array1[-1]

print('vlaue : ', value)
print(type(value))

vlaue :  9
<class 'numpy.int32'>


In [20]:
# array1을 2차원으로 변형

array1d = array1.copy()
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print('(row = 0, col = 0) index 가리키는 값 :',array2d[0,0])
print('(row = 0, col = 0) index 가리키는 값 :',array2d[0][1])

(row = 0, col = 0) index 가리키는 값 : 1
(row = 0, col = 0) index 가리키는 값 : 2


## 2.슬라이싱(Slicing) - 2차원

In [44]:
# print(array2d)  # 자르는게 슬라이싱임

print('array2d[(0:3,0:2) : \n\n',array2d[0:3,0:2])
print('array2d[(1:,0:3) : \n\n',array2d[1:,0:3])
print('array2d[(1:,:) : \n\n',array2d[1:,:])

array2d[(0:3,0:2) : 

 [[1 2]
 [4 5]
 [7 8]]
array2d[(1:,0:3) : 

 [[4 5 6]
 [7 8 9]]
array2d[(1:,:) : 

 [[4 5 6]
 [7 8 9]]


In [39]:
## question1
print(array2d)
print('\n')
print('array2d[(:2,0) : \n\n',array2d[:2,0])
print('\n')
print('array2d[(:2,0:1) : \n\n',array2d[:2,0:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array2d[(:2,0) : 

 [1 4]


array2d[(:2,0:1) : 

 [[1]
 [4]]


## 3.팬시 인덱싱(Fancy Indexing)

In [46]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
array2d[[0,1],[1,2]]

array([2, 6])

In [72]:
array2d[0:2,2]


array2d[[1,1],[0,1]]

# array_11d.ndim

array([4, 5])

In [77]:
array2d[[1,1]]

array([[4, 5, 6],
       [4, 5, 6]])

In [79]:
array2d[[1,1],[2,2]]

array([6, 6])

In [57]:
array2d[[0,1],2:]

# array_22d.ndim

array([[3],
       [6]])

NameError: name 'dd' is not defined